principal_homepage:
    path:     /
    defaults: { _controller: PrincipalBundle:Default:index }

# Login #

login:
    path:     /login
    defaults: { _controller: PrincipalBundle:Usuarios:login }

login_check:
    path:     /login_check

validacionLogin:
    path:     /validacionLogin
    defaults: { _controller: PrincipalBundle:Usuarios:validacionLogin }

# Dashboard # 

dashboard:
    path:     /dashboard
    defaults: {_controller: PrincipalBundle:Usuarios:dashboard }

# Logout #

logout:
    path:     /logout

# Usuarios #

listaUsuarios:
    path:     /listaUsuarios 
    defaults: { _controller: PrincipalBundle:Usuarios:listaUsuarios }

registroUsuario:
    path:     /registroUsuario
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuario }

actualizarEstado:
    path:     /actualizarEstado/{id}  
    defaults: { _controller: PrincipalBundle:Usuarios:actualizarEstado }

editarUsuario:
    path:     /editarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:editarUsuario }

eliminarUsuario:
    path:     /eliminarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:eliminarUsuario }

registroUsuarioGrupo:
    path:     /registroUsuarioGrupo/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuarioGrupo }

llenar:
    path:     /llenar
    defaults: { _controller: PrincipalBundle:Usuarios:llenar }

# Grupos #

leerArchivoTxt:
    path:     /leerArchivoTxt 
    defaults: { _controller: PrincipalBundle:Grupos:leerArchivoTxt }

grupos:
    path:     /grupos 
    defaults: { _controller: PrincipalBundle:Grupos:grupos }

aplicarCambiosSuperUsuario:
    path:     /aplicarCambiosSuperUsuario/{id} 
    defaults: { _controller: PrincipalBundle:Grupos:aplicarCambiosSuperUsuario }

aplicarCambios:
    path:     /aplicarCambios
    defaults: { _controller: PrincipalBundle:Grupos:aplicarCambios }

# Aliases #

grupos_aliases:
    path:     /grupos_aliases 
    defaults: { _controller: PrincipalBundle:Aliases:grupos_aliases }

registro_aliases:
    path:     /registro_aliases 
    defaults: { _controller: PrincipalBundle:Aliases:registro_aliases }

lista_aliases:
    path:     /lista_aliases 
    defaults: { _controller: PrincipalBundle:Aliases:lista_aliases }

editar_aliases:
    path:     /editar_aliases
    defaults: { _controller: PrincipalBundle:Aliases:editar_aliases }

eliminar_aliases:
    path:     /eliminar_aliases
    defaults: { _controller: PrincipalBundle:Aliases:eliminar_aliases }

crear_xml_aliases:
    path:     /crear_xml_aliases
    defaults: { _controller: PrincipalBundle:Aliases:crear_xml_aliases }

# Acl groups #

grupos_acl:
    path:     /grupos_acl 
    defaults: { _controller: PrincipalBundle:Acl:grupos_acl }

registro_acl:
    path:     /registro_acl 
    defaults: { _controller: PrincipalBundle:Acl:registro_acl }

lista_acl:
    path:     /lista_acl 
    defaults: { _controller: PrincipalBundle:Acl:lista_acl }

editar_acl:
    path:     /editar_acl/{id} 
    defaults: { _controller: PrincipalBundle:Acl:editar_acl }

eliminar_acl:
    path:     /eliminar_acl/{id} 
    defaults: { _controller: PrincipalBundle:Acl:eliminar_acl }

crear_xml_acl:
    path:     /crear_xml_acl
    defaults: { _controller: PrincipalBundle:Acl:crear_xml_acl }

# Target #

gruposTarget:
    path:     /gruposTarget 
    defaults: { _controller: PrincipalBundle:Target:gruposTarget }

registroTarget:
    path:     /registroTarget 
    defaults: { _controller: PrincipalBundle:Target:registroTarget }

editarTarget:
    path:     /editarTarget/{id} 
    defaults: { _controller: PrincipalBundle:Target:editarTarget }

listaTarget:
    path:     /listaTarget 
    defaults: { _controller: PrincipalBundle:Target:listaTarget }

eliminarTarget:
    path:     /eliminarTarget/{id} 
    defaults: { _controller: PrincipalBundle:Target:eliminarTarget }

crearXMLTarget:
    path:     /crearXMLTarget
    defaults: { _controller: PrincipalBundle:Target:crearXMLTarget }

# NatPortForward #

grupos_nat:
    path:     /grupos_nat
    defaults: { _controller: PrincipalBundle:NatPortForward:grupos_nat }

registro_nat_port_forward:
    path:     /registro_nat_port_forward 
    defaults: { _controller: PrincipalBundle:NatPortForward:registro_nat_port_forward }


gruposNat:
    path:     /gruposNat
    defaults: { _controller: PrincipalBundle:NatPortForward:gruposNat }

solicitudNatPort:
    path:     /solicitudNatPort 
    defaults: { _controller: PrincipalBundle:NatPortForward:solicitudNatPort }

registroNatPortForward:
    path:     /registroNatPortForward 
    defaults: { _controller: PrincipalBundle:NatPortForward:registroNatPortForward }

editarNatPortForward:
    path:     /editarNatPortForward/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:editarNatPortForward }

listaNat:
    path:     /listaNat 
    defaults: { _controller: PrincipalBundle:NatPortForward:listaNat }

eliminarNatPortForward:
    path:     /eliminarNatPortForward/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:eliminarNatPortForward }

crearXMLNat:
    path:     /crearXMLNat
    defaults: { _controller: PrincipalBundle:NatPortForward:crearXMLNat }

aplicarXMLNat:
    path:     /aplicarXMLNat/{id}
    defaults: { _controller: PrincipalBundle:NatPortForward:aplicarXMLNat }

dragAndDropNatPortForward:
    path:     /dragAndDropNatPortForward
    defaults: { _controller: PrincipalBundle:NatPortForward:dragAndDropNatPortForward }

registroNatOneToOne:
    path:     /registroNatOneToOne 
    defaults: { _controller: PrincipalBundle:NatPortForward:registroNatOneToOne }

editarNatOneToOne:
    path:     /editarNatOneToOne/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:editarNatOneToOne }

eliminarNatOneToOne:
    path:     /eliminarNatOneToOne/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:eliminarNatOneToOne }

dragAndDropNatOneToOne:
    path:     /dragAndDropNatOneToOne
    defaults: { _controller: PrincipalBundle:NatPortForward:dragAndDropNatOneToOne }

# Firewall #

gruposFirewall:
    path:     /gruposFirewall
    defaults: { _controller: PrincipalBundle:Firewall:gruposFirewall }

registroFirewallWan:
    path:     /registroFirewallWan 
    defaults: { _controller: PrincipalBundle:Firewall:registroFirewallWan }

editarFirewallWan:
    path:     /editarFirewallWan/{id} 
    defaults: { _controller: PrincipalBundle:Firewall:editarFirewallWan }

listaFirewallWan:
    path:     /listaFirewallWan 
    defaults: { _controller: PrincipalBundle:Firewall:listaFirewallWan }

eliminarFirewallWan:
    path:     /eliminarFirewallWan/{id} 
    defaults: { _controller: PrincipalBundle:Firewall:eliminarFirewallWan }

crearXMLFirewall:
    path:     /crearXMLFirewall
    defaults: { _controller: PrincipalBundle:Firewall:crearXMLFirewall }

aplicarXMLFirewallWan:
    path:     /aplicarXMLFirewallWan/{id}
    defaults: { _controller: PrincipalBundle:Firewall:aplicarXMLFirewallWan }

dragAndDropFirewallWan:
    path:     /dragAndDropFirewallWan
    defaults: { _controller: PrincipalBundle:Firewall:dragAndDropFirewallWan }

registroNatOneToOne:
    path:     /registroNatOneToOne 
    defaults: { _controller: PrincipalBundle:NatPortForward:registroNatOneToOne }

editarNatOneToOne:
    path:     /editarNatOneToOne/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:editarNatOneToOne }

eliminarNatOneToOne:
    path:     /eliminarNatOneToOne/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:eliminarNatOneToOne }

dragAndDropNatOneToOne:
    path:     /dragAndDropNatOneToOne
    defaults: { _controller: PrincipalBundle:NatPortForward:dragAndDropNatOneToOne }