principal_homepage:
    path:     /
    defaults: { _controller: PrincipalBundle:Default:index }

# Login #

login:
    path:     /login
    defaults: { _controller: PrincipalBundle:Usuarios:login }

login_check:
    path:     /login_check

validacionLogin:
    path:     /validacionLogin
    defaults: { _controller: PrincipalBundle:Usuarios:validacionLogin }

# Dashboard # 

dashboard:
    path:     /dashboard
    defaults: {_controller: PrincipalBundle:Usuarios:dashboard }

# Logout #

logout:
    path:     /logout

# Usuarios #

listaUsuarios:
    path:     /listaUsuarios 
    defaults: { _controller: PrincipalBundle:Usuarios:listaUsuarios }

registroUsuarios:
    path:     /registroUsuarios
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuarios }

actualizarEstado:
    path:     /actualizarEstado/{id}  
    defaults: { _controller: PrincipalBundle:Usuarios:actualizarEstado }

editarUsuario:
    path:     /editarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:editarUsuario }

recuperarPassword:
    path:     /recuperarPassword/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:recuperarPassword }

# Grupos #

leerArchivoTxt:
    path:     /leerArchivoTxt 
    defaults: { _controller: PrincipalBundle:Grupos:leerArchivoTxt }

grupos:
    path:     /grupos 
    defaults: { _controller: PrincipalBundle:Grupos:grupos }
