principal_homepage:
    path:     /
    defaults: { _controller: PrincipalBundle:Default:index }

# Login #

login:
    path:     /login
    defaults: { _controller: PrincipalBundle:Usuarios:login }

login_check:
    path:     /login_check

validacionLogin:
    path:     /validacionLogin
    defaults: { _controller: PrincipalBundle:Usuarios:validacionLogin }

# Dashboard # 

dashboard:
    path:     /dashboard
    defaults: {_controller: PrincipalBundle:Usuarios:dashboard }

# Logout #

logout:
    path:     /logout

# Usuarios #

listaUsuarios:
    path:     /listaUsuarios 
    defaults: { _controller: PrincipalBundle:Usuarios:listaUsuarios }

registroUsuario:
    path:     /registroUsuario
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuario }

actualizarEstado:
    path:     /actualizarEstado/{id}  
    defaults: { _controller: PrincipalBundle:Usuarios:actualizarEstado }

editarUsuario:
    path:     /editarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:editarUsuario }

eliminarUsuario:
    path:     /eliminarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:eliminarUsuario }

registroUsuarioGrupo:
    path:     /registroUsuarioGrupo/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuarioGrupo }

# Grupos #

leerArchivoTxt:
    path:     /leerArchivoTxt 
    defaults: { _controller: PrincipalBundle:Grupos:leerArchivoTxt }

grupos:
    path:     /grupos 
    defaults: { _controller: PrincipalBundle:Grupos:grupos }

aplicarCambiosSuperUsuario:
    path:     /aplicarCambiosSuperUsuario/{id} 
    defaults: { _controller: PrincipalBundle:Grupos:aplicarCambiosSuperUsuario }

aplicarCambios:
    path:     /aplicarCambios
    defaults: { _controller: PrincipalBundle:Grupos:aplicarCambios }

# Aliases #

registroAliases:
    path:     /registroAliases 
    defaults: { _controller: PrincipalBundle:Aliases:registroAliases }

editarAliases:
    path:     /editarAliases/{id} 
    defaults: { _controller: PrincipalBundle:Aliases:editarAliases }

# Acl groups #

registroAclGroups:
    path:     /registroAclGroups 
    defaults: { _controller: PrincipalBundle:AclGroups:registroAclGroups }