principal_homepage:
    path:     /
    defaults: { _controller: PrincipalBundle:Default:index }

# Login #

login:
    path:     /login
    defaults: { _controller: PrincipalBundle:Usuarios:login }

login_check:
    path:     /login_check

validacionLogin:
    path:     /validacionLogin
    defaults: { _controller: PrincipalBundle:Usuarios:validacionLogin }

# Dashboard # 

dashboard:
    path:     /dashboard
    defaults: {_controller: PrincipalBundle:Usuarios:dashboard }

# Logout #

logout:
    path:     /logout

# Usuarios #

listaUsuarios:
    path:     /listaUsuarios 
    defaults: { _controller: PrincipalBundle:Usuarios:listaUsuarios }

registroUsuario:
    path:     /registroUsuario
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuario }

actualizarEstado:
    path:     /actualizarEstado/{id}  
    defaults: { _controller: PrincipalBundle:Usuarios:actualizarEstado }

editarUsuario:
    path:     /editarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:editarUsuario }

eliminarUsuario:
    path:     /eliminarUsuario/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:eliminarUsuario }

registroUsuarioGrupo:
    path:     /registroUsuarioGrupo/{id}
    defaults: { _controller: PrincipalBundle:Usuarios:registroUsuarioGrupo }

# Grupos #

leerArchivoTxt:
    path:     /leerArchivoTxt 
    defaults: { _controller: PrincipalBundle:Grupos:leerArchivoTxt }

grupos:
    path:     /grupos 
    defaults: { _controller: PrincipalBundle:Grupos:grupos }

aplicarCambiosSuperUsuario:
    path:     /aplicarCambiosSuperUsuario/{id} 
    defaults: { _controller: PrincipalBundle:Grupos:aplicarCambiosSuperUsuario }

aplicarCambios:
    path:     /aplicarCambios
    defaults: { _controller: PrincipalBundle:Grupos:aplicarCambios }

# Aliases #

gruposAliases:
    path:     /gruposAliases 
    defaults: { _controller: PrincipalBundle:Aliases:gruposAliases }

registroAliases:
    path:     /registroAliases 
    defaults: { _controller: PrincipalBundle:Aliases:registroAliases }

editarAliases:
    path:     /editarAliases/{id} 
    defaults: { _controller: PrincipalBundle:Aliases:editarAliases }

listaAliases:
    path:     /listaAliases 
    defaults: { _controller: PrincipalBundle:Aliases:listaAliases }

eliminarAliases:
    path:     /eliminarAliases/{id} 
    defaults: { _controller: PrincipalBundle:Aliases:eliminarAliases }

crearXMLAliases:
    path:     /crearXMLAliases/{id}
    defaults: { _controller: PrincipalBundle:Aliases:crearXMLAliases }

aplicarXMLAliases:
    path:     /aplicarXMLAliases/{id}
    defaults: { _controller: PrincipalBundle:Aliases:aplicarXMLAliases }

# Acl groups #

gruposAcl:
    path:     /gruposAcl 
    defaults: { _controller: PrincipalBundle:Acl:gruposAcl }

registroAcl:
    path:     /registroAcl 
    defaults: { _controller: PrincipalBundle:Acl:registroAcl }

editarAcl:
    path:     /editarAcl/{id} 
    defaults: { _controller: PrincipalBundle:Acl:editarAcl }

listaAcl:
    path:     /listaAcl 
    defaults: { _controller: PrincipalBundle:Acl:listaAcl }

eliminarAcl:
    path:     /eliminarAcl/{id} 
    defaults: { _controller: PrincipalBundle:Acl:eliminarAcl }

crearXMLAcl:
    path:     /crearXMLAcl/{id}
    defaults: { _controller: PrincipalBundle:Acl:crearXMLAcl }

aplicarXMLAcl:
    path:     /aplicarXMLAcl/{id}
    defaults: { _controller: PrincipalBundle:Acl:aplicarXMLAcl }

# Target #

gruposTarget:
    path:     /gruposTarget 
    defaults: { _controller: PrincipalBundle:Target:gruposTarget }

registroTarget:
    path:     /registroTarget 
    defaults: { _controller: PrincipalBundle:Target:registroTarget }

editarTarget:
    path:     /editarTarget/{id} 
    defaults: { _controller: PrincipalBundle:Target:editarTarget }

listaTarget:
    path:     /listaTarget 
    defaults: { _controller: PrincipalBundle:Target:listaTarget }

eliminarTarget:
    path:     /eliminarTarget/{id} 
    defaults: { _controller: PrincipalBundle:Target:eliminarTarget }

crearXMLTarget:
    path:     /crearXMLTarget/{id}
    defaults: { _controller: PrincipalBundle:Target:crearXMLTarget }

aplicarXMLTarget:
    path:     /aplicarXMLTarget/{id}
    defaults: { _controller: PrincipalBundle:Target:aplicarXMLTarget }

# NatPortForward #

gruposNatPortForward:
    path:     /gruposNatPortForward 
    defaults: { _controller: PrincipalBundle:NatPortForward:gruposNatPortForward }

registroNatPortForward:
    path:     /registroNatPortForward 
    defaults: { _controller: PrincipalBundle:NatPortForward:registroNatPortForward }

editarNatPortForward:
    path:     /editarNatPortForward/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:editarNatPortForward }

listaNatPortForward:
    path:     /listaNatPortForward 
    defaults: { _controller: PrincipalBundle:NatPortForward:listaNatPortForward }

eliminarNatPortForward:
    path:     /eliminarNatPortForward/{id} 
    defaults: { _controller: PrincipalBundle:NatPortForward:eliminarNatPortForward }

crearXMLNatPortForward:
    path:     /crearXMLNatPortForward/{id}
    defaults: { _controller: PrincipalBundle:NatPortForward:crearXMLNatPortForward }

aplicarXMLNatPortForward:
    path:     /aplicarXMLNatPortForward/{id}
    defaults: { _controller: PrincipalBundle:NatPortForward:aplicarXMLNatPortForward }