<?php

namespace PrincipalBundle\Repository;

/**
 * AclGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
