<?php

namespace PrincipalBundle\Repository;

/**
 * AliasesDescripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasesDescripcionRepository extends \Doctrine\ORM\EntityRepository
{
}
