<?php

namespace PrincipalBundle\Repository;

/**
 * AliasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasesRepository extends \Doctrine\ORM\EntityRepository
{
}
