<?php

namespace PrincipalBundle\Repository;

/**
 * AliasesTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasesTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
