<?php

namespace PrincipalBundle\Repository;

/**
 * editarUsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class editarUsuariosRepository extends \Doctrine\ORM\EntityRepository
{
}
