<?php

namespace PrincipalBundle\Repository;

/**
 * FirewallLanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirewallLanRepository extends \Doctrine\ORM\EntityRepository
{
}
