<?php

namespace PrincipalBundle\Repository;

/**
 * GruposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruposRepository extends \Doctrine\ORM\EntityRepository
{
}
