<?php

namespace PrincipalBundle\Repository;

/**
 * InterfacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterfacesRepository extends \Doctrine\ORM\EntityRepository
{
}
