<?php

namespace PrincipalBundle\Repository;

/**
 * NatOneToOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatOneToOneRepository extends \Doctrine\ORM\EntityRepository
{
}
