<?php

namespace PrincipalBundle\Repository;

/**
 * NatPortForwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatPortForwardRepository extends \Doctrine\ORM\EntityRepository
{
}
