<?php

namespace PrincipalBundle\Repository;

/**
 * ProtocoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoloRepository extends \Doctrine\ORM\EntityRepository
{
}
