<?php

namespace PrincipalBundle\Repository;

/**
 * RedirectModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectModeRepository extends \Doctrine\ORM\EntityRepository
{
}
